#!/bin/sh
set -e

CONFIG_PATH="${CONFIG_PATH:-/data/config.yaml}"

if [ ! -f "$CONFIG_PATH" ]; then
  echo "Error: config file '$CONFIG_PATH' not found. Mount a prebaked config.yaml (generated by docker/run.sh)." >&2
  exit 1
fi

exec ./watgbridge "$CONFIG_PATH"
